/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 plane.gltf --transform
Author: dwsd (https://sketchfab.com/dwsd)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/f-14-tomcat-top-gun-gear-up-downloadable-9d2d0c87539046aa8c2198fcc47cdcf8
Title: F-14 Tomcat Top Gun (Gear UP) Downloadable
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("./3ds/plane-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[0, 64.37, 123.76]} rotation={[-Math.PI, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.White} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.White} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.White_0} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.White_0} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.White_1} />
      </group>
    </group>
  );
}

useGLTF.preload("./3ds/plane-transformed.glb");
